services:
  db:
    container_name: db
    image: postgres:13-alpine
    volumes:
      - pg_base:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - 5432:5432
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${DB_USER} -d ${DB_NAME}"
        ]
      interval: 2s
      timeout: 3s
      retries: 40
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}

  app:
    container_name: app
    build: .
    command: sh -c "alembic upgrade head && python daily.py"
    ports:
      - 5000:5000
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./src:/app
    env_file:
      - .env

volumes:
  pg_base:
    external: true