"""Add nullable columns

Revision ID: 5410ce2c25b6
Revises: 6fb8d6850112
Create Date: 2024-07-17 01:24:03.361317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5410ce2c25b6'
down_revision: Union[str, None] = '6fb8d6850112'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
