"""Initial migration

Revision ID: 6fb8d6850112
Revises: 
Create Date: 2024-07-16 20:19:13.200079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fb8d6850112'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proposicao',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('presentationDate', sa.DateTime(), nullable=True),
    sa.Column('ementa', sa.String(), nullable=True),
    sa.Column('regime', sa.String(), nullable=True),
    sa.Column('situation', sa.String(), nullable=True),
    sa.Column('propositionType', sa.String(), nullable=True),
    sa.Column('number', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tramitacao',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('local', sa.String(), nullable=True),
    sa.Column('propositionId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['propositionId'], ['proposicao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tramitacao')
    op.drop_table('proposicao')
    # ### end Alembic commands ###
